


import type { Metadata } from "next";
import { Exo } from "next/font/google";
import "./globals.css";
import { cn } from "@/lib/utils";
import Navbar from "@/components/Navbarr/Navbar";
import { Toaster } from "sonner";
import WrapeSession from "@/components/WrapeSession/WrapeSession";
import CartContextProvider from "./_context/CartContextProvider";
import { getCartData } from "./cart/cartAction";
import { CartResponse } from "./cart/cartInterface";
import { getwishlistData } from "./wishlist/cartAction";
import { WishlistResponse } from "./wishlist/cartInterface";

const inter = Exo({ subsets: ['latin'], variable: '--font-Exo' });


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const req: WishlistResponse | null = await getwishlistData()
  const res: CartResponse | null = await getCartData()

  return (
    <html lang="en" className={cn("font-sans", inter.variable)}>
      <body
        className={`  antialiased`}
      >
        <CartContextProvider res={res} req={req}>


          <WrapeSession>
            <Navbar />
            {children}
            <Toaster />
          </WrapeSession>

        </CartContextProvider>
      </body>
    </html>
  );
}
